backend:
  name: git-gateway
  branch: main

collections:
  - name: articles
    label: Articles
    files:
      - label: Published articles
        name: articles
        file: data/articles.json
        fields:
          - label: Articles
            name: articles
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Web address, name: slug, widget: string }
              - { label: Date, name: date, widget: datetime, format: YYYY-MM-DD, time_format: false }
              - { label: Category, name: category, widget: string }
              - { label: Summary, name: excerpt, widget: text }
              - { label: Article, name: body, widget: markdown }
